language: node_js
node_js:
 - "8"
 - "node"
script:
  - yarn run lint
  - yarn run test-ci
after_success:
  - yarn run coveralls-ci
  - yarn global add typedoc && yarn run doc
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: documentation
  on:
    branch: master