language: node_js
node_js:
 - "8"
 - "node"
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn run lint
  - yarn run test-ci
  - lerna run browser
after_success:
  - yarn run coveralls-ci
  - yarn global add typedoc && yarn run doc
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: documentation
  on:
    branch: master
    node_js: "node"
