sudo: required
services:
 - docker
language: node_js
node_js:
 - "8"
 - "10"
 - "node"
os:
 - linux
 - osx
# - windows # Temporary disabled, not very stable yet on Travis
before_install: yarn global add greenkeeper-lockfile@1
install: yarn install --pure-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn run lint
  - yarn run test-ci
  - lerna run browser
  - lerna run spec
after_success:
  - yarn run coveralls-ci
  - yarn global add typedoc && yarn run doc
cache:
  yarn: true
  directories:
    - node_modules
    - .rdf-test-suite-cache
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    local-dir: documentation
    on:
      tags: false
      branch: master
      node_js: "node"
      os: "linux"
  - provider: script
    skip-cleanup: true
    script: ./.travis/docker.sh && ./.travis/docker.sh push
    on:
      tags: true
      all_branches: true
      node_js: "node"
      os: "linux"
  - provider: script
    skip-cleanup: true
    script: ./.travis/deploy_browser.sh
    on:
      tags: false
      branch: master
      node_js: "node"
      os: "linux"
  - provider: script
    skip-cleanup: true
    script: ./.travis/deploy_browser.sh
    on:
      tags: true
      all_branches: true
      node_js: "node"
      os: "linux"
